### PR TITLE
Non-wellfounded trees (spreads & fans) [WIP]

### PR DESCRIPTION
**Pull request by jonsterling**
This is _work-in-progress_, but presented for comment.
- [x] Add abstract `Fan` type & view
- [ ] Implement standard type class instances for `Fan`
- [ ] Add abstract `Spread` type & view
- [ ] Implement standard type class instances for `Spread`
- [x] Move `Data.{Fan,Spread}` to `Data.Tree.{Fan,Spread}` (I think)

### CODE REVIEW

**Comment by matthieubulte** [comment]
> Move Data.{Fan,Spread} to Data.Tree.{Fan,Spread} (I think)

yep

**Comment by jplatte** [comment]
We might want to consider the names of the types in `Data.Tree.Fan` and `Data.Tree.Spread`. Do we want `Fan` and `Spread`, or just `Tree` three times in three different modules, like `Data.List.Lazy` has a second `List` type?

I don't have a strong opinion on this, just wanted to mention it.
Having all types have the same name might make it clearer to a few users that these are just variations of the same thing, while having distinct names would probably make more sense for people who already know the terms `Fan` and `Spread`, and would also make it easier to import multiple of these modules in one place.

**Comment by jonsterling** [comment]
I'm fine with alternative names, but they'd have to be more elaborate and hard to type than "Lazy", since we're dealing with laziness of one or two dimensions.

Best,
Jon

**Comment by jplatte** [comment]
I'm not talking about changing the names `Fan` and `Spread`, I'm fine with those. I'm talking about the `data` declaration in each of them. If the types should be `Data.Tree.Fan.Fan` and `Data.Tree.Spread.Spread` or `Data.Tree.Fan.Tree` and `Data.Tree.Spread.Tree`.

**Comment by jonsterling** [comment]
oh, interesting idea. that might be a good way to go!

**Comment by jplatte** [comment]
Well, I'll just guess the one you think might be a good way to go is the one you didn't do before and probably didn't consider, which would be `Tree` as type name in all three modules.

Anyway, I just ticked off the smallest item on the TODO list, hope you don't mind me adding stuff to your branch.

**Comment by jonsterling** [comment]
thanks for making the change! :smile:

**Pull request closed without merging**
